--ERROR CODE
SELECT ERROR  
   FROM TABLE(DEVOPS_BI_CLOUD_WEBSERVICE.LP_LOG_VIEW_F('GXPET',91229,1))
   WHERE ERROR 
   LIKE '%Duplicate ODI session%'
   ;
   
   
--------------------------------------------------------------------------------
--TABLE USED TO TEST 

CREATE TABLE W_ETLDASH_CLOUD_CDP_REDUCED (
  SESS_NO     NUMBER,
  NAME        VARCHAR2(256),
  NB_RUN      NUMBER
  )
;
INSERT INTO W_ETLDASH_CLOUD_CDP_REDUCED (
    SESS_NO,
    NAME,
    NB_RUN 
)
SELECT 
  SESS_NO, 
  NAME, 
  NB_RUN 
FROM W_ETLDASH_CLOUD_CDP_HISTORY_S
WHERE UPPER(STATUS) LIKE 'FAILED'
AND SESS_NO IN (107960,
107951,
107954,
107944,
107943,
107931,
107930,
107926,
107924,
107923
)
;

COMMIT;
SELECT * FROM W_ETLDASH_CLOUD_CDP_REDUCED;
TRUNCATE TABLE W_ETLDASH_CLOUD_CDP_REDUCED;


--------------------------------------------------------------------------------
--TABLE TO BE USED BY THE DASHBOARD IN ORDER TO CHECK FOR THE ERROR WITH THE SESSION NUMBER

SELECT SESS_NO, NAME, NB_RUN FROM W_ETLDASH_CLOUD_CDP_HISTORY_S
WHERE UPPER(STATUS) LIKE 'FAILED';

DESCRIBE W_ETLDASH_CLOUD_CDP_HISTORY_S;

SELECT * FROM DBA_OBJECTS 
WHERE OBJECT_NAME LIKE 'FAILED_SESSIONS_ERROR_TEST';

CREATE TABLE FAILED_SESSIONS_ERROR_TEST (
  SESS_NO     NUMBER,
  NAME        VARCHAR2(256),
  NB_RUN      NUMBER,
  ERROR_MSS VARCHAR2(4000)
  )
;
SELECT * FROM FAILED_SESSIONS_ERROR_TEST;
TRUNCATE TABLE FAILED_SESSIONS_ERROR_TEST;
----------------------------------------------------------------
--PL/SQL

DECLARE

DB_ENV          VARCHAR2(500);
ERROR_MSS_LOOP  VARCHAR2(4000);

BEGIN

  SELECT ENVIRONMENT INTO DB_ENV   FROM W_ETL_DASH_WEBSERVICE_MAP WHERE GCW_ENVIRONMENT =  SUBSTR(ora_database_name,0,5)  AND ENVIRONMENT LIKE 'CDP%OCI'   AND INACTIVE_FLG = 'N' AND ROWNUM = 1 ;
  
  DBMS_OUTPUT.PUT_LINE(DB_ENV);

  FOR FAILED_RECORD IN (
    SELECT 
      SESS_NO, 
      NAME, 
      NB_RUN 
    FROM W_ETLDASH_CLOUD_CDP_REDUCED
  ) 
  LOOP
    
    SELECT ERROR INTO ERROR_MSS_LOOP
    FROM TABLE(DEVOPS_BI_CLOUD_WEBSERVICE.LP_LOG_VIEW_F(DB_ENV,FAILED_RECORD.SESS_NO,FAILED_RECORD.NB_RUN));

    INSERT INTO FAILED_SESSIONS_ERROR_TEST (
      SESS_NO,
      NAME,
      NB_RUN,
      ERROR_MSS
    )
    VALUES(
    FAILED_RECORD.SESS_NO,
    FAILED_RECORD.NAME,
    FAILED_RECORD.NB_RUN,
    ERROR_MSS_LOOP
    );  
  
  END LOOP;
  COMMIT;

END;
/